function ambientes = get_ambientes()
    ambientes = {'hogar', 'trabajo', 'estudios', 'compras', 'visitas', ...
        'salud', 'tramites', 'recreo', 'tPublico', 'auto',...
        'caminata', 'bicicleta', 'otro'};
end